name: budget_manager_app
description: A Flutter budget management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  url_launcher: ^6.2.2
  table_calendar: ^3.1.3
  fl_chart: ^0.69.2
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
